var express = require('express');
var router = express.Router();

const itemList= [{'ID':1, 'Term':'DevOps', 'Description':'DevOps is a software development and IT operations methodology that emphasizes collaboration, automation, and continuous delivery, aiming to shorten development cycles, increase deployment frequency, and improve overall software quality.', 'References':'GitLab, “DevOps explained,” GitLab, May 23, 2022. https://about.gitlab.com/topics/devops/'},
{'ID':2, 'Term':'Agile', 'Description':'An iterative development approach that promotes collaboration, adaptability, and customer-centricity, delivering value incrementally and fostering continuous improvement in software development and operations.', 'References':'Atlassian, “Agile best practices and tutorials | Atlassian,” Atlassian, 2019. https://www.atlassian.com/agile4'},
{'ID':3, 'Term':'CI/CD (Continuous Integration/Continuous Deployment)', 'Description':'Automates code integration, testing, and deployment, ensuring a streamlined development process with faster feedback loops and more frequent, reliable software releases.', 'References':'"GenRocket.” https://www.genrocket.com/test-data-management-lp1/?gclid=CjwKCAjw8ZKmBhArEiwAspcJ7qkrCaMa1dxRP2trFOwgu5DBpanjgdiIKgZdz6zLbe6V_rC8vnSJchoCp7sQAvD_BwE (accessed Jul. 29, 2023).'},
{'ID':4, 'Term':'Infrastructure as Code (IaC)', 'Description':'Treats infrastructure configurations as software, enabling automated provisioning and management of resources, reducing manual errors, and promoting version control for infrastructure changes.', 'References':'"What is Infrastructure as Code (IaC)?,” www.redhat.com. https://www.redhat.com/en/topics/automation/what-is-infrastructure-as-code-iac#:~:text=Infrastructure%20as%20Code%20(IaC)%20is'},
{'ID':5, 'Term':'Site Reliability Engineering (SRE)', 'Description':' Blends software engineering and IT operations to maintain highly reliable systems, emphasizing error budgeting, monitoring, and incident response for sustainable and scalable services.', 'References':'Atlassian, “Love DevOps? Wait until you meet SRE,” Atlassian. https://www.atlassian.com/incident-management/devops/sre'},
{'ID':6, 'Term':'Docker', 'Description':'A containerization platform that simplifies application deployment by packaging software and its dependencies into isolated containers, ensuring consistency across various environments.', 'References':'“Docker vs Virtual Machine (VM) – Key Differences You Should Know,” freeCodeCamp.org, Oct. 04, 2022. https://www.freecodecamp.org/news/docker-vs-vm-key-differences-you-should-know/#:~:text=A%20docker%20container%20is%20a (accessed Jul. 30, 2023).'},
{'ID':7, 'Term':'Microservices', 'Description':'Architectural style where an application is divided into small, independent services, enabling flexibility, scalability, and faster development and deployment of individual components.', 'References':'“What are Microservices? | AWS,” Amazon Web Services, Inc. https://aws.amazon.com/microservices/#:~:text=Microservices%20are%20an%20architectural%20and'},
{'ID':8, 'Term':'Version Control', 'Description':'Systematic management of code changes, facilitating collaboration, tracking history, and enabling rollbacks, vital for effective teamwork in DevOps environments.', 'References':'Atlassian, “What is version control | Atlassian Git Tutorial,” Atlassian. https://www.atlassian.com/git/tutorials/what-is-version-control#:~:text=Version%20control%2C%20also%20known%20as'},
{'ID':9, 'Term':'Jenkins', 'Description':'An open-source automation server used for CI/CD pipelines, automating build, test, and deployment processes, integrating with various tools to support continuous delivery.', 'References':'“What is Jenkins? | Jenkins For Continuous Integration,” Edureka, Nov. 07, 2016. https://www.edureka.co/blog/what-is-jenkins/#:~:text=Jenkins%20is%20an%20open%2Dsource'},
{'ID':10, 'Term':'Monitoring and Alerting', 'Description':'Practices to observe system health and performance, enabling rapid response to issues, minimizing downtime, and ensuring optimal user experiences.', 'References':'sematext, “The Complete Guide to Metrics, Alerting & Monitoring,” Sematext, Jul. 29, 2020. https://sematext.com/blog/monitoring-alerting/'},
{'ID':11, 'Term':'Configuration Management', 'Description':'Automates and tracks changes to system configurations, ensuring consistency and reducing manual setup errors, a critical aspect of maintaining infrastructure.', 'References':'“What is Configuration Management?,” VMware, Jan. 05, 2023. https://www.vmware.com/au/topics/glossary/content/configuration-management.html#:~:text=Configuration%20Management%20is%20the%20process'},
{'ID':12, 'Term':'Orchestration', 'Description':'Coordinates and automates complex tasks or workflows, often used in provisioning, scaling, and managing distributed systems and containers.', 'References':'“Definition of ORCHESTRATION,” www.merriam-webster.com, Aug. 04, 2023. https://www.merriam-webster.com/dictionary/orchestration#:~:text=1 (accessed Aug. 13, 2023).'},
{'ID':13, 'Term':'Continuous Monitoring', 'Description':'Real-time observation of system performance, user interactions, and application metrics to identify issues promptly, leading to quicker problem resolution.', 'References':'“What Is Continuous Monitoring? Benefits & Best Practices - CrowdStrike,” crowdstrike.com. https://www.crowdstrike.com/cybersecurity-101/observability/continuous-monitoring/'},
{'ID':14, 'Term':'Immutable Infrastructure:', 'Description':'Treats infrastructure as unchangeable, rebuilding it for each update, enhancing stability, reproducibility, and minimizing configuration drift.', 'References':'“Immutable Infrastructure: Benefits, Comparisons & More,” HashiCorp. https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure'},
{'ID':15, 'Term':'Infrastructure as a Service (IaaS)', 'Description':'Cloud computing model providing virtualized computing resources over the internet, enabling scalable and on-demand infrastructure provisioning.', 'References':'M. Boisvert, “What is IaaS? Infrastructure as a Service Definition,” SearchCloudComputing, Nov. 2022. https://www.techtarget.com/searchcloudcomputing/definition/Infrastructure-as-a-Service-IaaS'},
{'ID':16, 'Term':'Platform as a Service (PaaS)', 'Description':'Cloud service offering a platform for application development and deployment, abstracting underlying infrastructure complexities, and accelerating software delivery.', 'References':'“What is PaaS? Platform as a Service | Microsoft Azure,” azure.microsoft.com. https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-paas'},
{'ID':17, 'Term':'Infrastructure as Code (IaC) Tools', 'Description':'Tools like Terraform and Ansible allow defining infrastructure configurations in code, enabling automated provisioning, scaling, and management of resources.', 'References':'“Best Infrastructure as Code Tools (IaC): The Top 10 for 2022,” bluelight.co. https://bluelight.co/blog/best-infrastructure-as-code-tools'},
{'ID':18, 'Term':'Blue-Green Deployment', 'Description':'A release strategy where two identical environments (blue and green) are maintained, allowing seamless and near-zero downtime updates by switching between them.', 'References':'“Blue/Green Deployments - Overview of Deployment Options on AWS,” docs.aws.amazon.com. https://docs.aws.amazon.com/whitepapers/latest/overview-deployment-options/bluegreen-deployments.html'},
{'ID':19, 'Term':'Feature Flags', 'Description':'Enable toggling specific features on/off dynamically, promoting controlled experimentation, phased releases, and reducing the risk of deploying new functionalities.', 'References':'“Feature Toggles (aka Feature Flags),” martinfowler.com. https://martinfowler.com/articles/feature-toggles.html'},
{'ID':20, 'Term':'DevSecOps', 'Description':'Integrates security practices into the DevOps workflow, prioritizing security at every stage, ensuring robust protection, and reducing vulnerabilities in the software development lifecycle.', 'References':'“What Is DevSecOps and How Does It Work? | Synopsys,” www.synopsys.com. https://www.synopsys.com/glossary/what-is-devsecops.html'},
{'ID':21, 'Term':'Continuous Deployment (CD)', 'Description':'An extension of Continuous Integration, it automates the release process to push code changes to production as soon as they pass automated tests, reducing deployment delays.', 'References':'Redhat, “What is CI/CD?,” Redhat.com, 2019. Available: https://www.redhat.com/en/topics/devops/what-is-ci-cd'},
{'ID':22, 'Term':'Container Orchestration', 'Description':'Tools like Kubernetes manage and automate the deployment, scaling, and management of containerized applications, ensuring high availability and resource optimization.', 'References':'“What is container orchestration?,” www.redhat.com. Available: https://www.redhat.com/en/topics/containers/what-is-container-orchestration?sc_cid=7013a000003SfSLAA0&gclid=CjwKCAjwr_CnBhA0EiwAci5sikRDw12VmH5DVZeh1P3ZJjxM0eNp7OeU7Md-87mONh5IXgSWT5dpRBoC06cQAvD_BwE.'},
{'ID':23, 'Term':'Infrastructure as Code (IaC) Templates', 'Description':'hese files define infrastructure configurations using code, making it easy to provision and manage resources consistently and reproducibly.', 'References':'K. Mokris, “Shift Left: Securing Infrastructure-as-Code Templates,” Complete Cloud Security in Minutes - Orca Security, Aug. 10, 2022. Available: https://orca.security/resources/blog/secure-iac-templates-with-shift-left-security/#:~:text=Infrastructure%2Das%2DCode%20(IaC,and%20deploy%20applications%20more%20efficiently.'},
{'ID':24, 'Term':'Serverless Computing', 'Description':' A cloud computing model where the cloud provider automatically manages server resources, enabling developers to focus solely on code, improving scalability and reducing operational overhead.', 'References':'“What is serverless computing? |  Serverless definition Cloudflare,” Cloudflare. Available: https://www.cloudflare.com/learning/serverless/what-is-serverless/'},
{'ID':25, 'Term':'Deployment Pipeline', 'Description':'A series of automated steps (build, test, deploy) that code goes through before reaching production, ensuring reliability and consistency in software delivery.', 'References':'“What is a Deployment Pipeline?,” PagerDuty. Available: https://www.pagerduty.com/resources/learn/what-is-a-deployment-pipeline/#:~:text=In%20software%20development%2C%20a%20deployment'},
{'ID':26, 'Term':'Version Control System (VCS)', 'Description':'Tools like Git track changes to source code, allowing multiple developers to collaborate, manage code history, and resolve conflicts efficiently.', 'References':'Atlassian, “What is version control,” Atlassian, 2019. Available: https://www.atlassian.com/git/tutorials/what-is-version-control'},
{'ID':27, 'Term':'Incident Management', 'Description':'The process of identifying, responding to, and resolving incidents to minimize downtime and maintain service reliability, often using tools like incident tracking systems.', 'References':'“What is Incident Management? - ServiceNow,” servicenow.com. Available: https://www.servicenow.com/products/itsm/what-is-incident-management.html'},
{'ID':28, 'Term':'Metrics and KPIs', 'Description':'Key Performance Indicators (KPIs) and metrics provide data-driven insights into system health, application performance, and user experience, aiding in decision-making and optimization.', 'References':'“What is the Difference Between a KPI and a Metric?,” AgencyAnalytics. Available: https://agencyanalytics.com/blog/kpi-vs-metric'},
{'ID':29, 'Term':'Scalability', 'Description':'The ability of a system to handle increased workload or demand by adding resources, ensuring performance and availability during traffic spikes.', 'References':'“How to Scale DevOps: 5 Keys to Success,” www.qovery.com. Available: https://www.qovery.com/blog/how-to-scale-devops-5-keys-to-success'},
{'ID':30, 'Term':'Feedback Loops', 'Description':'Mechanisms for collecting user and system data to provide insights into software quality and user satisfaction, helping teams make informed decisions and prioritize improvements.', 'References':'A. Weiss, “Understanding Feedback Loops in DevOps,” Medium, Jul. 30, 2018. Available: https://medium.com/@antweiss/understanding-feedback-loops-in-devops-e93b92b74bd1.'},
{'ID':31, 'Term':'Chaos Engineering', 'Description':' practice of deliberately injecting faults or failures into a system to test its resilience and identify weaknesses. It helps ensure systems can withstand unexpected issues.', 'References':'“PRINCIPLES OF CHAOS ENGINEERING - Principles of chaos engineering,” principlesofchaos.org. https://principlesofchaos.org/'},
{'ID':32, 'Term':'Log Aggregation', 'Description':'The process of collecting and centralizing logs from various sources to make them easily searchable and analyzable, aiding in debugging and monitoring.', 'References':'“Log management,” Wikipedia, Mar. 06, 2020. https://en.wikipedia.org/wiki/Log_management'},
{'ID':33, 'Term':'Infrastructure as a Service (IaaS)', 'Description':'Cloud computing service that offers virtualized computing resources over the internet, allowing users to provision and manage infrastructure components.', 'References':'[3]“What is IaaS? Infrastructure as a Service | Microsoft Azure,” azure.microsoft.com. https://azure.microsoft.com/en-us/resources/cloud-computing-dictionary/what-is-iaas/#alert-ocf853 (accessed Sep. 22, 2023).'},
{'ID':34, 'Term':'Platform as a Service (PaaS)', 'Description':'Cloud service providing a platform for application development and deployment, abstracting infrastructure management complexities. ', 'References':'“What is PaaS? Platform as a Service | Microsoft Azure,” azure.microsoft.com. https://azure.microsoft.com/en-au/resources/cloud-computing-dictionary/what-is-paas#:~:text=What%20is%20PaaS%3F-'},
{'ID':35, 'Term':'Secret Management', 'Description':'Practices and tools for securely storing, distributing, and managing sensitive information such as API keys, passwords, and certificates. ', 'References':'“Secret Manager,” Google Cloud. https://cloud.google.com/secret-manager (accessed Sep. 22, 2023).'},
{'ID':36, 'Term':'Infrastructure Automation', 'Description':'The use of scripts and tools to automate the provisioning, configuration, and management of infrastructure resources, enhancing consistency and efficiency.', 'References':'A. Weiss, “Understanding Feedback Loops in DevOps,” Medium, Jul. 30, 2018. Available: https://medium.com/@antweiss/understanding-feedback-loops-in-devops-e93b92b74bd1.'},
{'ID':37, 'Term':'Change Management', 'Description':'A systematic approach to planning, tracking, and controlling changes to software systems, ensuring they are implemented with minimal disruption and risk.', 'References':'A. Weiss, “Understanding Feedback Loops in DevOps,” Medium, Jul. 30, 2018. Available: https://medium.com/@antweiss/understanding-feedback-loops-in-devops-e93b92b74bd1.'},
{'ID':38, 'Term':'Continuous Verification', 'Description':'A practice of continuously validating and ensuring that changes meet predefined quality, security, and compliance criteria before deployment.', 'References':'A. Weiss, “Understanding Feedback Loops in DevOps,” Medium, Jul. 30, 2018. Available: https://medium.com/@antweiss/understanding-feedback-loops-in-devops-e93b92b74bd1.'},
{'ID':39, 'Term':'Blue-Green Deployment', 'Description':'A release strategy where two identical environments (blue and green) are maintained, allowing for seamless and low-risk updates by switching between them.', 'References':'“bliki: BlueGreenDeployment,” martinfowler.com. https://martinfowler.com/bliki/BlueGreenDeployment.html'},
{'ID':40, 'Term':'Immutable Infrastructure', 'Description':'reating infrastructure as unchangeable, rebuilding it for each update, which enhances stability, reproducibility, and reduces configuration drift.', 'References':'HashiCorp, “Immutable Infrastructure: Benefits, Comparisons & More,” HashiCorp. https://www.hashicorp.com/resources/what-is-mutable-vs-immutable-infrastructure'},

]


/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'DevOps Glossary', subheading:'my website showing a collection of DevOps term and their brief description.', item:itemList });
});

module.exports = router;
